services:
  app:
    ipc: host
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        UID: ${UID:-1000}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: sleep infinity
    volumes:
      - type: bind
        source: .
        target: /home/ubuntu/app/
        consistency: delegated
